---
language: cpp

sudo: enabled

compiler:
  - g++

matrix:
  include:
    - name: CUDA 10
      env:
        - CUDA=10.1.243-3
        - CUDA_SHORT=10.1
        - UBUNTU_VERSION=ubuntu2004
      dist: focal
      addons:
        apt:
          packages:
            - cmake
            - libhdf5-dev
            - libhdf5-103
            - libhdf5-serial-dev
            - libhdf5-cpp-103
            - python3.8
            - python3.8-dev
            - pybind11-dev
	    - nvidia-cuda-toolkit
	    - nvidia-cuda-dev


before_install:
#  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
#  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
#  - sudo dpkg -i ${INSTALLER}
#  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
#  - sudo apt-key add 7fa2af80.pub
#  - sudo apt update -qq
#  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
#  - sudo apt clean
#  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
#  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
#  - PATH=${CUDA_HOME}/bin:${PATH}
  - PATH=${PATH}:${PWD}
  - mkdir ~/THOR_download
  - mkdir /tmp/THOR_download/
  - wget 'https://github.com/exoclime/THOR/archive/dev.zip' -O '/tmp/THOR_download/dev.zip'
  - unzip /tmp/THOR_download/dev.zip -d /tmp/THOR_download/
  - mkdir build
  - cd build
  - cmake -DTHOR_BASE_FOLDER=/tmp/THOR_download/THOR-dev/ ..

script:
  - make 

